name: WF1

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: my-dev

    steps:
      - uses: actions/checkout@v2

      - run: |
          mmm='${{ secrets.sec1 }}'
          echo $mmm
          echo ${mmm^^}

  job2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          mmm='${{ secrets.sec1 }}'
          echo $mmm
          echo ${mmm^^}

